//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnaCherchel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentComputer
    {
        public int id { get; set; }
        public string Type { get; set; }
        public int Number { get; set; }
        public int Index_doc { get; set; }
        public System.DateTime Date { get; set; }
        public int Pages { get; set; }
        public System.DateTime Date_start { get; set; }
        public System.DateTime Date_end { get; set; }
    }
}
