//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnaCherchel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArchEntities2 : DbContext
    {
        public ArchEntities2()
            : base("name=ArchEntities2")
        {
        }

        private static ArchEntities2 _instance;

        public static ArchEntities2 GetContext()
        {
            if (_instance == null) _instance = new ArchEntities2();
            return _instance;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<DocumentComputer> DocumentComputer { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<UserTim> UserTim { get; set; }
    }
}
